version: '3.4'

networks:
  excursionbookingapp:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver_container_3
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - excursionbookingapp
  excursionbooking:
    container_name: app_container
    image: ${DOCKER_REGISTRY-}excursionbooking
    build:
      context: .
      dockerfile: ExcursionBooking/Dockerfile
    ports:
    - "8082:80"
    - "8083:443"
    depends_on:
      - sqlserver
    environment:
    - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=keypass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/excursionbooking.pfx
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=8082
    - ASPNETCORE_HTTPS_PORTS=8083
    - DB_HOST=sqlserver_container
    - DB_NAME=ExcursionBooking
    - DB_SA_PASSWORD=Password123
    volumes:
    - /c/Users/bobko/Development/Tour-Booking-Web-Site/ssl/site:/https      
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
     - excursionbookingapp
volumes:
  sqlserver_data: